name = "telebase"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "TELEBASE_KV"
id = "3a197fb397ad42f58fb03ad20a4f9cf3"
